// The explicit barrel both the runtime client and drizzle-kit read, so there is
// exactly one schema surface and one migration flow.
//
// `auth-schema.ts` is GENERATED by `npx auth@latest generate` (the `auth`
// package — `@better-auth/cli` is frozen at 1.4 and emits a schema that does not
// match the 1.6 runtime). Do not hand-edit it: the next regeneration silently
// discards the edit. Domain tables belong in their own files alongside this one
// and are re-exported here.
export * from "./auth-schema"
export * from "./customer"
export * from "./locker"
export * from "./locker-size"
export * from "./package"
export * from "./pricing"
export * from "./station"
